### ISSUE TITLE
Fix email validation on registration for full TLD (e.g. test@test)

### ISSUE THREAD

**Issue by R-Eli-Levasseur** [jwflory/django-rit-grasa#146] opened 2019-11-05 03:08 UTC
# Summary

Email validation fails on register and add admin, I was able to enter test@test

# Affected components

- [ ] Authentication
- [ ] Event curation system
- [ ] Search
- [ ] Admin portal
- [X] Other (explain below)

Registering users

# Suggested fix

**Comment by justwheel** [comment] 2019-11-05 12:09
@eguy006 This might be working as designed since a valid email address might not include a TLD (e.g. `test@localhost`). For this reason, validation probably works when you use `test@test` as an email.

It would be worth checking if validation doesn't work for other mistakes, e.g. `test!test.com`.

**Comment by justwheel** [comment] 2019-11-17 20:56
As it happened, @leong96 figured out a way to do this in #207 by handling an exception for an invalid email address. So this was actually a back-end fix after all!

![Screenshot of feedback from back-end when an invalid email address is entered, not caught by front-end validation](https://user-images.githubusercontent.com/4721034/69013784-f1aeff00-0951-11ea-986f-3ebeddd75dd4.png "Screenshot of feedback from back-end when an invalid email address is entered, not caught by front-end validation")

Closing as complete. :clapper:

**Closed as completed by justwheel** 2019-11-17 20:56 UTC
Labels: bug, backend
